### ISSUE TITLE
[BUG]: Image Search App: MODEL_DIM is passed as string to create_collection

### ISSUE THREAD

**Issue by dnoliver** [milvus-io/bootcamp#1467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running the app in a container using Docker for Desktop

This is the Dockerfile:

```
FROM docker.io/library/python:3.11
WORKDIR /usr/src/app
COPY ./bootcamp/tutorials/quickstart/apps/image_search_with_milvus/requirements.txt .
RUN pip install -r requirements.txt
COPY ./bootcamp/tutorials/quickstart/apps/image_search_with_milvus/ .
CMD streamlit run app.py
```

And this is my compose service file:

```
milvus-db:
    image: milvusdb/milvus:v2.4.16
    container_name: milvus-db
    security_opt:
      - seccomp:unconfined
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local
    volumes:
      - milvus-data:/var/lib/milvus
      - ./src/milvus-db/embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
      - ./src/milvus-db/user.yaml:/milvus/configs/user.yaml
    ports:
      - "19530:19530"
      - "9091:9091"
      - "2379:2379"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s
    command: ["milvus", "run", "standalone"]
ingestion-pipeline:
    image: web-ui
    container_name: ingestion-pipeline
    build:
      context: .
      dockerfile: src/web-ui/Dockerfile
    environment:
      MILVUS_ENDPOINT: http://milvus-db:19530
      MILVUS_TOKEN: *********
      COLLECTION_NAME: my_image_collection
      MODEL_NAME: resnet34
      MODEL_DIM: 512
    depends_on:
      - milvus-db
    command: python ./insert.py /tmp/frames
    volumes:
      - "filtered-frames:/tmp/frames/cars/"
```

`ingestion-pipeline` runs insert.py. But it crashes because `os.getenv("MODEL_DIM")` returns `"512"` (in string format):

```
ingestion-pipeline  | 2024-11-26 22:11:20.441 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
ingestion-pipeline  | 2024-11-26 22:11:20.517 
ingestion-pipeline  |   Warning: to view this Streamlit app on a browser, run it with the following
ingestion-pipeline  |   command:
ingestion-pipeline  |
ingestion-pipeline  |     streamlit run ./insert.py [ARGUMENTS]
ingestion-pipeline  | 2024-11-26 22:11:20.518 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
ingestion-pipeline  | 2024-11-26 22:11:20.518 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
ingestion-pipeline  | 2024-11-26 22:11:20.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
ingestion-pipeline  | 2024-11-26 22:11:20.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
ingestion-pipeline  | RPC error: [create_collection], <MilvusException: (code=65535, message=strconv.ParseInt: parsing "\"512\"": invalid syntax)>, <Time:{'RPC start': '2024-11-26 22:11:20.637509', 'RPC error': '2024-11-26 22:11:20.649503'}>
ingestion-pipeline  | Failed to create collection: my_image_collection
ingestion-pipeline  | Traceback (most recent call last):
ingestion-pipeline  |   File "/usr/src/app/./insert.py", line 25, in <module>
ingestion-pipeline  |     create_collection(
ingestion-pipeline  |   File "/usr/src/app/milvus_utils.py", line 19, in create_collection
ingestion-pipeline  |     return milvus_client.create_collection(
ingestion-pipeline  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ingestion-pipeline  |   File "/usr/local/lib/python3.11/site-packages/pymilvus/milvus_client/milvus_client.py", line 80, in create_collection
ingestion-pipeline  |     return self._fast_create_collection(
ingestion-pipeline  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ingestion-pipeline  |   File "/usr/local/lib/python3.11/site-packages/pymilvus/milvus_client/milvus_client.py", line 140, in _fast_create_collection
ingestion-pipeline  |     raise ex from ex
ingestion-pipeline  |   File "/usr/local/lib/python3.11/site-packages/pymilvus/milvus_client/milvus_client.py", line 136, in _fast_create_collection
ingestion-pipeline  |     conn.create_collection(collection_name, schema, timeout=timeout, **kwargs)
ingestion-pipeline  |   File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 141, in handler
ingestion-pipeline  |     raise e from e
ingestion-pipeline  |   File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 137, in handler
ingestion-pipeline  |     return func(*args, **kwargs)
ingestion-pipeline  |            ^^^^^^^^^^^^^^^^^^^^^
ingestion-pipeline  |   File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 176, in handler
ingestion-pipeline  |     return func(self, *args, **kwargs)
ingestion-pipeline  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ingestion-pipeline  |   File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 116, in handler
ingestion-pipeline  |     raise e from e
ingestion-pipeline  |   File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 86, in handler
ingestion-pipeline  |     return func(*args, **kwargs)
ingestion-pipeline  |            ^^^^^^^^^^^^^^^^^^^^^
ingestion-pipeline  |   File "/usr/local/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 310, in create_collection
ingestion-pipeline  |     check_status(status)
ingestion-pipeline  |   File "/usr/local/lib/python3.11/site-packages/pymilvus/client/utils.py", line 63, in check_status
ingestion-pipeline  |     raise MilvusException(status.code, status.reason, status.error_code)
ingestion-pipeline  | pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=strconv.ParseInt: parsing "\"512\"": invalid syntax)>
ingestion-pipeline exited with code 1
```

I have a fix for that: casting the value to int. Will do a PR

### Expected Behavior

It should work. When I was running it on windows it worked fine, using the .env file

### Steps To Reproduce

```markdown
1. Build the container with the definition posted above
2. Run the container with compose
```

### Software version

```markdown
Server: milvusdb/milvus:v2.4.16
Client: pymilvus 2.5.0
```
